### ISSUE TITLE
Uncaught TypeError: Failed to execute 'item' on 'HTMLCollection': 1 argument required, but only 0...

### ISSUE THREAD

**Issue by bsisic** [afj176/bitcoin-status-bar#1]
**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [bitcoin-status-bar](https://github.com/afj176/bitcoin-status-bar) package 0.2.0

### Stack Trace

Uncaught TypeError: Failed to execute 'item' on 'HTMLCollection': 1 argument required, but only 0 present.

```
At /Users/bsisic/.atom/packages/bitcoin-status-bar/lib/bitcoin-view.coffee:66

TypeError: Failed to execute 'item' on 'HTMLCollection': 1 argument required, but only 0 present.
    at HTMLElement.BitcoinView.hasParent (/packages/bitcoin-status-bar/lib/bitcoin-view.coffee:66:14)
    at HTMLElement.BitcoinView.toggle (/packages/bitcoin-status-bar/lib/bitcoin-view.coffee:60:9)
    at /packages/bitcoin-status-bar/lib/bitcoin-view.coffee:11:8)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:17.4.0 bitcoin-status-bar:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-clock 0.1.15 
atom-ide-ui 0.7.0 
atom-material-ui 2.0.6 
bitcoin-status-bar 0.2.0 
busy-signal 1.4.3 
file-bookmark 1.0.3 
file-icons 2.1.14 
git-plus 7.10.0 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-typescript 0.7.2 
intentions 1.1.5 
js-hyperclick 1.12.2 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
multirow-tabs 0.3.3 
now-syntax 0.2.4 
pigments 0.40.2 
ti-create 0.30.0 
titanium-alloy 0.14.6 
unity-dark-ui 2.0.9 
unity-ui 2.1.11 
```

**Comment by afj176** [comment]
been a long time but I am going to fix this.

**Comment by afj176** [comment]
resolved in latest version.
